import withNuxt from './.nuxt/eslint.config.mjs'

export default withNuxt(
	{
		ignores: [
			'dist', // autogenerated by Nuxt
			'.output', // autogenerated by Nuxt
			'.nuxt', // autogenerated by Nuxt
			'node_modules',
			'prismicio-types.d.ts',
			'.agents', // vendored third-party skill scripts, not project code
			'.claude', // vendored third-party skill scripts, not project code
			'backup', // generated content/schema migration snapshots
			'old-site-hugotomasi', // mirror of the previous WordPress site, kept for migration reference only
		],
	},
).append({
	rules: {
		// ✅ Autorise les tabs comme indentation
		'@stylistic/no-tabs': ['error', { allowIndentationTabs: true }],

		// ✅ Force l’indentation avec tab
		'@stylistic/indent': ['error', 'tab'],

		// ✅ Idem pour les lignes de continuation d’opérateurs binaires (||, +, unions de type...)
		// — sans ça cette règle réclame des espaces et entre en conflit avec no-mixed-spaces-and-tabs.
		'@stylistic/indent-binary-ops': ['error', 'tab'],
	},
}).append({
	files: ['app/slices/**/index.vue'],
	rules: {
		// Prismic slice components are conventionally folder-named (app/slices/<Name>/index.vue) —
		// the file itself is always "index", not a real single-word component name issue.
		'vue/multi-word-component-names': 'off',
	},
})
