import withNuxt from './.nuxt/eslint.config.mjs'

export default withNuxt(
    {
        ignores: [
            'dist', // autogenerated by Nuxt
            '.output', // autogenerated by Nuxt
            '.nuxt', // autogenerated by Nuxt
            'node_modules',
            'prismicio-types.d.ts',
            '.agents', // vendored third-party skill scripts, not project code
            '.claude', // vendored third-party skill scripts, not project code
            'backup', // generated content/schema migration snapshots
            'old-site-hugotomasi', // mirror of the previous WordPress site, kept for migration reference only
        ],
    },
).append({
    rules: {
        // ✅ Force l’indentation avec 4 espaces
        '@stylistic/indent': ['error', 4],

        // ✅ Idem pour les lignes de continuation d’opérateurs binaires (||, +, unions de type...)
        '@stylistic/indent-binary-ops': ['error', 4],
    },
}).append({
    files: ['app/slices/**/index.vue'],
    rules: {
        // Prismic slice components are conventionally folder-named (app/slices/<Name>/index.vue) —
        // the file itself is always "index", not a real single-word component name issue.
        'vue/multi-word-component-names': 'off',
    },
})
